//
//  APNsConfig.swift
//  Khandoba Secure Docs
//
//  Generated by configure_apns.sh
//

import Foundation
import Combine

struct APNsConfig {
    static let keyID = "PR62QK662L"
    static let teamID = "Q5Y8754WU4"
    static let bundleID = "com.khandoba.securedocs"
    
    // APNs environment
    #if DEBUG
    static let environment = "development"
    #else
    static let environment = "production"
    #endif
}
