#!/bin/bash

# Script to guide adding extensions via Xcode
# Note: Xcode doesn't support adding targets via command line
# This script provides step-by-step instructions

set -e

echo "📱 Extension Setup Guide"
echo "========================="
echo ""
echo "Xcode doesn't support adding targets via command line."
echo "Follow these steps in Xcode to add extensions:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  ADD SHARE EXTENSION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   a. File → New → Target"
echo "   b. Select 'iOS' → 'Share Extension'"
echo "   c. Click 'Next'"
echo "   d. Configure:"
echo "      - Product Name: ShareExtension"
echo "      - Bundle Identifier: com.khandoba.securedocs.ShareExtension"
echo "      - Language: Swift"
echo "      - Include UI Extension: ✅ (checked)"
echo "   e. Click 'Finish'"
echo "   f. DO NOT activate scheme when prompted"
echo ""
echo "   g. Replace generated files:"
echo "      - Delete auto-generated ShareExtensionViewController.swift"
echo "      - Copy our custom files from:"
echo "        • ShareExtension/ShareExtensionViewController.swift"
echo "        • ShareExtension/Info.plist (replace generated)"
echo "        • ShareExtension/ShareExtension.entitlements"
echo ""
echo "   h. Configure Build Settings:"
echo "      - General → Display Name: 'Khandoba'"
echo "      - Build Settings → INFOPLIST_FILE: ShareExtension/Info.plist"
echo "      - Build Settings → GENERATE_INFOPLIST_FILE: NO"
echo "      - Build Settings → SWIFT_ACTIVE_COMPILATION_CONDITIONS: \$(inherited) APP_EXTENSION"
echo ""
echo "   i. Signing & Capabilities:"
echo "      - Enable automatic signing"
echo "      - Add App Groups: group.com.khandoba.securedocs"
echo "      - Add iCloud: iCloud.com.khandoba.securedocs"
echo ""
echo "   j. File System Sync (Build Phases):"
echo "      - Add 'Khandoba Secure Docs' folder to fileSystemSynchronizedGroups"
echo "      - Add exception for Info.plist from 'Khandoba Secure Docs' folder"
echo ""
echo "   k. Embed Extension (Main App Target):"
echo "      - Select 'Khandoba Secure Docs' target"
echo "      - General → Frameworks, Libraries, and Embedded Content"
echo "      - Add ShareExtension.appex → Embed & Sign"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "2️⃣  ADD MESSAGE EXTENSION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   a. File → New → Target"
echo "   b. Select 'iOS' → 'iMessage Extension'"
echo "   c. Click 'Next'"
echo "   d. Configure:"
echo "      - Product Name: MessageExtension"
echo "      - Bundle Identifier: com.khandoba.securedocs.MessageExtension"
echo "      - Language: Swift"
echo "      - Include UI Extension: ✅ (checked)"
echo "   e. Click 'Finish'"
echo "   f. DO NOT activate scheme when prompted"
echo ""
echo "   g. Replace generated files:"
echo "      - Delete auto-generated MessageExtensionViewController.swift"
echo "      - Copy our custom files from:"
echo "        • MessageExtension/MessageExtensionViewController.swift"
echo "        • MessageExtension/Info.plist (replace generated)"
echo "        • MessageExtension/MessageExtension.entitlements"
echo ""
echo "   h. Configure Build Settings:"
echo "      - General → Display Name: 'Khandoba'"
echo "      - Build Settings → INFOPLIST_FILE: MessageExtension/Info.plist"
echo "      - Build Settings → GENERATE_INFOPLIST_FILE: NO"
echo "      - Build Settings → SWIFT_ACTIVE_COMPILATION_CONDITIONS: \$(inherited) APP_EXTENSION"
echo ""
echo "   i. Signing & Capabilities:"
echo "      - Enable automatic signing"
echo "      - Add App Groups: group.com.khandoba.securedocs"
echo "      - Add iCloud: iCloud.com.khandoba.securedocs"
echo ""
echo "   j. File System Sync (Build Phases):"
echo "      - Add 'Khandoba Secure Docs' folder to fileSystemSynchronizedGroups"
echo "      - Add exception for Info.plist from 'Khandoba Secure Docs' folder"
echo ""
echo "   k. Embed Extension (Main App Target):"
echo "      - Select 'Khandoba Secure Docs' target"
echo "      - General → Frameworks, Libraries, and Embedded Content"
echo "      - Add MessageExtension.appex → Embed & Sign"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "3️⃣  VERIFY CONFIGURATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   Run: xcodebuild -project 'Khandoba Secure Docs.xcodeproj' -list"
echo "   Should show both ShareExtension and MessageExtension targets"
echo ""
echo "   Build: xcodebuild -project 'Khandoba Secure Docs.xcodeproj' -scheme 'Khandoba Secure Docs' -configuration Debug"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Follow these steps in Xcode to complete the setup"
echo ""

