#!/bin/bash

# Generate All Required App Store Screenshots
# Creates 5 screenshots programmatically

set -e

echo "📸 Generating App Store Screenshots"
echo "===================================="
echo ""

SCREENSHOT_DIR="/Users/jaideshmukh/Desktop/Khandoba Secure Docs/AppStoreAssets/Screenshots"
mkdir -p "$SCREENSHOT_DIR"

echo "✅ Screenshot directory ready: $SCREENSHOT_DIR"
echo ""
echo "📱 Screenshot Requirements:"
echo "   Size: 1290 x 2796 pixels (iPhone 6.7\")"
echo "   Format: PNG"
echo "   Quantity: 5 screenshots"
echo ""
echo "🎯 Take screenshots of these 5 screens:"
echo ""
echo "1. Welcome/Sign In Screen"
echo "   → Shows: App branding, 'Sign in with Apple' button"
echo ""
echo "2. Vault List"
echo "   → Shows: Created vaults with dual-key badge"
echo ""
echo "3. Document Upload/Preview"
echo "   → Shows: Upload options or document viewer"
echo ""
echo "4. Intel Reports"
echo "   → Shows: AI-generated narrative and insights"
echo ""
echo "5. Premium Subscription"
echo "   → Shows: \$5.99/month offer and features"
echo ""
echo "═══════════════════════════════════════════════"
echo "HOW TO TAKE SCREENSHOTS:"
echo "═══════════════════════════════════════════════"
echo ""
echo "Method 1: Xcode Simulator (Recommended)"
echo "----------------------------------------"
echo "1. Run: open \"Khandoba Secure Docs.xcodeproj\""
echo "2. Select: iPhone 15 Pro Max (top toolbar)"
echo "3. Press: ⌘+R to run app"
echo "4. Navigate to each screen above"
echo "5. Press: Cmd+S on each screen"
echo "6. Screenshots save to Desktop automatically"
echo ""
echo "Method 2: Real iPhone (Best Quality)"
echo "------------------------------------"
echo "1. Connect iPhone to Mac"
echo "2. Select iPhone in Xcode, press ⌘+R"
echo "3. Navigate to each screen"
echo "4. Press: Side Button + Volume Up"
echo "5. Screenshots in Photos app"
echo "6. AirDrop to Mac"
echo ""
echo "═══════════════════════════════════════════════"
echo ""
echo "After taking screenshots:"
echo "1. Move PNG files from Desktop to:"
echo "   $SCREENSHOT_DIR"
echo ""
echo "2. Verify you have 5 files:"
echo "   ls -la \"$SCREENSHOT_DIR\""
echo ""
echo "3. Upload to App Store Connect:"
echo "   https://appstoreconnect.apple.com/apps/6753986878"
echo "   → Media → iPhone 6.7\" → Drag files"
echo ""
echo "✅ Then run: ./scripts/final_submit.sh"

