#!/bin/bash

# Complete extension setup script
# Recreates extension folders and provides Xcode setup instructions

set -e

echo "🔧 Extension Setup Script"
echo "========================="
echo ""

# Create directories
echo "📁 Creating extension directories..."
mkdir -p ShareExtension
mkdir -p MessageExtension
echo "   ✅ Created ShareExtension/"
echo "   ✅ Created MessageExtension/"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 NEXT STEPS: Add Extensions in Xcode"
echo ""
echo "Since Xcode doesn't support adding targets via command line,"
echo "you need to add them manually in Xcode:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  REMOVE OLD TARGETS (if they still exist)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   a. Open Xcode project"
echo "   b. Project Navigator → Find 'ShareExtension' and 'MessageExtension' targets"
echo "   c. Right-click each → Delete → Move to Trash"
echo "   d. Select main app target → General → Remove embedded .appex files"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "2️⃣  ADD SHARE EXTENSION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   File → New → Target → iOS → Share Extension"
echo ""
echo "   Configuration:"
echo "   • Product Name: ShareExtension"
echo "   • Bundle ID: com.khandoba.securedocs.ShareExtension"
echo "   • Language: Swift"
echo "   • Include UI Extension: ✅"
echo ""
echo "   After creation:"
echo "   • Replace generated files with files from ShareExtension/ folder"
echo "   • Configure Info.plist (see docs/EXTENSION_IMPLEMENTATION_GUIDE.md)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "3️⃣  ADD MESSAGE EXTENSION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   File → New → Target → iOS → iMessage Extension"
echo ""
echo "   Configuration:"
echo "   • Product Name: MessageExtension"
echo "   • Bundle ID: com.khandoba.securedocs.MessageExtension"
echo "   • Language: Swift"
echo "   • Include UI Extension: ✅"
echo ""
echo "   After creation:"
echo "   • Replace generated files with files from MessageExtension/ folder"
echo "   • Configure Info.plist (see docs/EXTENSION_IMPLEMENTATION_GUIDE.md)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📚 Full guide: docs/EXTENSION_IMPLEMENTATION_GUIDE.md"
echo ""
echo "✅ Extension directories ready"
echo ""

