#!/bin/bash

# Setup Share Extension for Khandoba Secure Docs
# This script helps configure the Share Extension target in Xcode

set -e

PROJECT_NAME="Khandoba Secure Docs"
PROJECT_FILE="${PROJECT_NAME}.xcodeproj"
BUNDLE_ID="com.khandoba.securedocs"
SHARE_EXT_BUNDLE_ID="${BUNDLE_ID}.ShareExtension"
APP_GROUP="group.com.khandoba.securedocs"

echo "🔧 Setting up Share Extension for ${PROJECT_NAME}"
echo ""

# Check if project exists
if [ ! -d "$PROJECT_FILE" ]; then
    echo "❌ Error: Project file not found: $PROJECT_FILE"
    exit 1
fi

echo "✅ Project file found"
echo ""

# Instructions for manual setup
echo "📋 MANUAL SETUP INSTRUCTIONS:"
echo ""
echo "Since Xcode project configuration requires GUI interaction, please follow these steps:"
echo ""
echo "1. Open the project in Xcode:"
echo "   open \"${PROJECT_FILE}\""
echo ""
echo "2. Add Share Extension Target:"
echo "   - File → New → Target"
echo "   - iOS → Share Extension"
echo "   - Product Name: ShareExtension"
echo "   - Bundle Identifier: ${SHARE_EXT_BUNDLE_ID}"
echo "   - Language: Swift"
echo "   - Embed in Application: ${PROJECT_NAME}"
echo ""
echo "3. Configure Share Extension:"
echo "   - Select ShareExtension target"
echo "   - General tab:"
echo "     - Display Name: Khandoba"
echo "     - Deployment Target: iOS 17.0"
echo "   - Signing & Capabilities:"
echo "     - Add App Groups capability"
echo "     - App Group: ${APP_GROUP}"
echo "     - Add CloudKit capability"
echo "     - Container: iCloud.com.khandoba.securedocs"
echo ""
echo "4. Replace ShareExtensionViewController.swift:"
echo "   - Delete the auto-generated ShareExtensionViewController.swift"
echo "   - Copy ShareExtension/ShareExtensionViewController.swift to the target"
echo ""
echo "5. Add Info.plist:"
echo "   - Add ShareExtension/Info.plist to the target"
echo "   - In Build Settings, set Info.plist File path to: ShareExtension/Info.plist"
echo ""
echo "6. Add Entitlements:"
echo "   - Add ShareExtension/ShareExtension.entitlements to the target"
echo "   - In Build Settings, set Code Signing Entitlements to: ShareExtension/ShareExtension.entitlements"
echo ""
echo "7. Link Required Frameworks:"
echo "   - Build Phases → Link Binary With Libraries:"
echo "     - SwiftUI.framework"
echo "     - SwiftData.framework"
echo "     - UniformTypeIdentifiers.framework"
echo ""
echo "8. Share Data Models:"
echo "   - Add Models folder to ShareExtension target"
echo "   - Ensure Vault.swift, Document.swift, User.swift are included"
echo ""
echo "9. Build and Test:"
echo "   - Select ShareExtension scheme"
echo "   - Build (Cmd+B)"
echo "   - Run on device/simulator"
echo "   - Test sharing from Photos app"
echo ""
echo "✅ Setup complete!"
echo ""
echo "📱 To test:"
echo "   1. Build and run the app"
echo "   2. Open Photos app"
echo "   3. Select a photo"
echo "   4. Tap Share → Khandoba"
echo "   5. Select a vault and import"
echo ""

