//
//  MessageExtensionViewController.swift
//  Khandoba Secure Docs
//
//  iMessage Extension for sending nominee invitations
//

import UIKit
import Messages
import SwiftUI
import SwiftData

class MessageExtensionViewController: MSMessagesAppViewController {
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    // MARK: - Conversation Handling
    
    override func willBecomeActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the inactive to active state
        presentNomineeInvitationView(for: conversation)
    }
    
    override func didResignActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the active to inactive state
    }
    
    override func didReceive(_ message: MSMessage, conversation: MSConversation) {
        // Called when a message arrives that was generated by another instance of this
        // extension on a remote device
    }
    
    override func didStartSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user taps the send button
    }
    
    override func didCancelSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user deletes the message without sending it
    }
    
    // MARK: - Transition Handling
    
    override func willTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called before the extension transitions to a new presentation style
        removeAllChildViewControllers()
    }
    
    override func didTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called after the extension transitions to a new presentation style
    }
    
    // MARK: - Nominee Invitation
    
    private func presentNomineeInvitationView(for conversation: MSConversation) {
        // Remove any existing child view controllers
        removeAllChildViewControllers()
        
        // Create the SwiftUI view for nominee invitation
        let invitationView = NomineeInvitationMessageView(
            conversation: conversation,
            onSendInvitation: { [weak self] inviteToken, vaultName, recipientName in
                self?.sendNomineeInvitation(
                    inviteToken: inviteToken,
                    vaultName: vaultName,
                    recipientName: recipientName,
                    in: conversation
                )
            },
            onCancel: { [weak self] in
                self?.dismiss()
            }
        )
        
        // Embed SwiftUI view
        let hostingController = UIHostingController(rootView: invitationView)
        addChild(hostingController)
        hostingController.view.frame = view.bounds
        hostingController.view.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        view.addSubview(hostingController.view)
        hostingController.didMove(toParent: self)
    }
    
    private func sendNomineeInvitation(
        inviteToken: String,
        vaultName: String,
        recipientName: String,
        in conversation: MSConversation
    ) {
        // Create the invitation URL
        let baseURL = "khandoba://nominee/invite"
        var components = URLComponents(string: baseURL)
        components?.queryItems = [
            URLQueryItem(name: "token", value: inviteToken),
            URLQueryItem(name: "vault", value: vaultName)
        ]
        
        guard let url = components?.url else {
            print("❌ Failed to create invitation URL")
            return
        }
        
        // Create message layout
        let layout = MSMessageTemplateLayout()
        layout.caption = "You've been invited to access vault: \(vaultName)"
        layout.subcaption = "Tap to accept invitation"
        layout.trailingCaption = "Khandoba"
        
        // Create message
        let message = MSMessage()
        message.layout = layout
        message.url = url
        message.summaryText = "Vault Invitation: \(vaultName)"
        
        // Insert message into conversation
        conversation.insert(message) { error in
            if let error = error {
                print("❌ Failed to send invitation: \(error.localizedDescription)")
            } else {
                print("✅ Nominee invitation sent via iMessage")
                // Request presentation style to compact to show the message
                self.requestPresentationStyle(.compact)
            }
        }
    }
    
    private func removeAllChildViewControllers() {
        for child in children {
            child.willMove(toParent: nil)
            child.view.removeFromSuperview()
            child.removeFromParent()
        }
    }
}

// MARK: - SwiftUI View for Nominee Invitation

struct NomineeInvitationMessageView: View {
    let conversation: MSConversation
    let onSendInvitation: (String, String, String) -> Void
    let onCancel: () -> Void
    
    @State private var vaultName: String = ""
    @State private var inviteToken: String = ""
    @State private var recipientName: String = ""
    @State private var isLoading = false
    
    var body: some View {
        NavigationView {
            Form {
                Section(header: Text("Vault Invitation")) {
                    TextField("Vault Name", text: $vaultName)
                    TextField("Invite Token", text: $inviteToken)
                    TextField("Recipient Name", text: $recipientName)
                }
                
                Section {
                    Button(action: {
                        guard !vaultName.isEmpty, !inviteToken.isEmpty else { return }
                        isLoading = true
                        onSendInvitation(inviteToken, vaultName, recipientName)
                        isLoading = false
                    }) {
                        if isLoading {
                            ProgressView()
                        } else {
                            Text("Send Invitation")
                        }
                    }
                    .disabled(vaultName.isEmpty || inviteToken.isEmpty || isLoading)
                }
            }
            .navigationTitle("Invite Nominee")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .navigationBarLeading) {
                    Button("Cancel", action: onCancel)
                }
            }
        }
    }
}

