//
//  MessageExtensionViewController.swift
//  Khandoba Secure Docs
//
//  iMessage Extension for sending nominee invitations
//

import UIKit
import Messages
import SwiftUI
import SwiftData

class MessageExtensionViewController: MSMessagesAppViewController {
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    // MARK: - Conversation Handling
    
    override func willBecomeActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the inactive to active state
        presentNomineeInvitationView(for: conversation)
    }
    
    override func didResignActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the active to inactive state
    }
    
    override func didReceive(_ message: MSMessage, conversation: MSConversation) {
        // Called when a message arrives that was generated by another instance of this
        // extension on a remote device
    }
    
    override func didStartSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user taps the send button
    }
    
    override func didCancelSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user deletes the message without sending it
    }
    
    // MARK: - Transition Handling
    
    override func willTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called before the extension transitions to a new presentation style
        removeAllChildViewControllers()
    }
    
    override func didTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called after the extension transitions to a new presentation style
    }
    
    // MARK: - Nominee Invitation
    
    private func presentNomineeInvitationView(for conversation: MSConversation) {
        // Remove any existing child view controllers
        removeAllChildViewControllers()
        
        // Create the SwiftUI view for nominee invitation
        let invitationView = NomineeInvitationMessageView(
            conversation: conversation,
            onSendInvitation: { [weak self] inviteToken, vaultName, recipientName in
                self?.sendNomineeInvitation(
                    inviteToken: inviteToken,
                    vaultName: vaultName,
                    recipientName: recipientName,
                    in: conversation
                )
            },
            onCancel: { [weak self] in
                self?.dismiss()
            }
        )
        
        // Embed SwiftUI view with UnifiedTheme environment
        let hostingController = UIHostingController(
            rootView: invitationView
                .environment(\.unifiedTheme, UnifiedTheme())
        )
        addChild(hostingController)
        hostingController.view.frame = view.bounds
        hostingController.view.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        view.addSubview(hostingController.view)
        hostingController.didMove(toParent: self)
    }
    
    private func sendNomineeInvitation(
        inviteToken: String,
        vaultName: String,
        recipientName: String,
        in conversation: MSConversation
    ) {
        // Create the invitation URL
        let baseURL = "khandoba://nominee/invite"
        var components = URLComponents(string: baseURL)
        components?.queryItems = [
            URLQueryItem(name: "token", value: inviteToken),
            URLQueryItem(name: "vault", value: vaultName)
        ]
        
        guard let url = components?.url else {
            print("❌ Failed to create invitation URL")
            return
        }
        
        // Create message layout with visible link
        let layout = MSMessageTemplateLayout()
        layout.caption = "🔐 Vault Invitation"
        layout.subcaption = "You've been invited to access vault: \(vaultName)"
        layout.trailingCaption = "Khandoba"
        
        // Create message with deep link
        let message = MSMessage()
        message.layout = layout
        message.url = url
        message.summaryText = "Vault Invitation: \(vaultName) - Tap to accept"
        
        // Add the invitation URL as text in the message for visibility
        // This ensures the recipient can see and tap the link
        let invitationText = """
        🔐 Vault Invitation
        
        You've been invited to access vault: \(vaultName)
        
        Tap the message bubble above to accept, or open this link:
        \(url.absoluteString)
        
        Sent via Khandoba Secure Docs
        """
        
        // Note: MSMessage doesn't support adding custom text directly
        // The URL in message.url will be tappable when the message is received
        // The recipient needs to tap the message bubble to open the app
        
        // Insert message into conversation
        conversation.insert(message) { error in
            if let error = error {
                print("❌ Failed to send invitation: \(error.localizedDescription)")
            } else {
                print("✅ Nominee invitation sent via iMessage")
                // Request presentation style to compact to show the message
                self.requestPresentationStyle(.compact)
            }
        }
    }
    
    private func removeAllChildViewControllers() {
        for child in children {
            child.willMove(toParent: nil)
            child.view.removeFromSuperview()
            child.removeFromParent()
        }
    }
}

// MARK: - SwiftUI View for Nominee Invitation

struct NomineeInvitationMessageView: View {
    let conversation: MSConversation
    let onSendInvitation: (String, String, String) -> Void
    let onCancel: () -> Void
    
    @Environment(\.unifiedTheme) var theme
    @Environment(\.colorScheme) var colorScheme
    
    @State private var vaultName: String = ""
    @State private var recipientName: String = ""
    @State private var phoneNumber: String = ""
    @State private var email: String = ""
    @State private var isLoading = false
    @State private var vaults: [Vault] = []
    @State private var selectedVault: Vault?
    @State private var pendingNominees: [Nominee] = []
    @State private var selectedNominee: Nominee?
    @State private var showError = false
    @State private var errorMessage = ""
    @State private var modelContext: ModelContext?
    
    var body: some View {
        let colors = theme.colors(for: colorScheme)
        
        NavigationStack {
            ZStack {
                colors.background
                    .ignoresSafeArea()
                
                ScrollView {
                    VStack(spacing: UnifiedTheme.Spacing.lg) {
                        // Vault Selection
                        VStack(alignment: .leading, spacing: UnifiedTheme.Spacing.xs) {
                            Text("Select Vault")
                                .font(theme.typography.subheadline)
                                .foregroundColor(colors.textSecondary)
                            
                            if vaults.isEmpty {
                                HStack {
                                    ProgressView()
                                        .scaleEffect(0.8)
                                    Text("Loading vaults...")
                                        .font(theme.typography.body)
                                        .foregroundColor(colors.textSecondary)
                                }
                                .padding(UnifiedTheme.Spacing.md)
                                .frame(maxWidth: .infinity)
                                .background(colors.surface)
                                .cornerRadius(UnifiedTheme.CornerRadius.lg)
                            } else {
                                Picker("Vault", selection: $selectedVault) {
                                    ForEach(vaults) { vault in
                                        Text(vault.name).tag(vault as Vault?)
                                    }
                                }
                                .pickerStyle(.menu)
                                .padding(UnifiedTheme.Spacing.md)
                                .background(colors.surface)
                                .cornerRadius(UnifiedTheme.CornerRadius.lg)
                                .onChange(of: selectedVault) { newValue in
                                    if let vault = newValue {
                                        vaultName = vault.name
                                        loadPendingNominees(for: vault)
                                    }
                                }
                            }
                        }
                        
                        // Pending Nominees (if any) - for resending invitations
                        if !pendingNominees.isEmpty {
                            VStack(alignment: .leading, spacing: UnifiedTheme.Spacing.xs) {
                                Text("Pending Invitations (Tap to Resend)")
                                    .font(theme.typography.subheadline)
                                    .foregroundColor(colors.textSecondary)
                                
                                StandardCard {
                                    VStack(spacing: UnifiedTheme.Spacing.sm) {
                                        ForEach(pendingNominees) { nominee in
                                            Button {
                                                selectedNominee = nominee
                                                recipientName = nominee.name
                                                phoneNumber = nominee.phoneNumber ?? ""
                                                email = nominee.email ?? ""
                                            } label: {
                                                HStack {
                                                    VStack(alignment: .leading, spacing: 4) {
                                                        Text(nominee.name)
                                                            .font(theme.typography.body)
                                                            .foregroundColor(colors.textPrimary)
                                                            .fontWeight(.medium)
                                                        if let phone = nominee.phoneNumber {
                                                            Text(phone)
                                                                .font(theme.typography.caption)
                                                                .foregroundColor(colors.textSecondary)
                                                        }
                                                        Text("Status: \(nominee.status)")
                                                            .font(theme.typography.caption2)
                                                            .foregroundColor(colors.textTertiary)
                                                    }
                                                    Spacer()
                                                    if selectedNominee?.id == nominee.id {
                                                        Image(systemName: "checkmark.circle.fill")
                                                            .foregroundColor(colors.primary)
                                                    }
                                                }
                                            }
                                            
                                            if nominee.id != pendingNominees.last?.id {
                                                Divider()
                                                    .background(colors.textTertiary)
                                            }
                                        }
                                    }
                                }
                            }
                        }
                        
                        // Invitation Details
                        VStack(alignment: .leading, spacing: UnifiedTheme.Spacing.xs) {
                            Text("Recipient Name")
                                .font(theme.typography.subheadline)
                                .foregroundColor(colors.textSecondary)
                            
                            TextField("Recipient name", text: $recipientName)
                                .font(theme.typography.body)
                                .padding(UnifiedTheme.Spacing.md)
                                .background(colors.surface)
                                .cornerRadius(UnifiedTheme.CornerRadius.lg)
                                .disabled(selectedNominee != nil)
                        }
                        
                        VStack(alignment: .leading, spacing: UnifiedTheme.Spacing.xs) {
                            Text("Phone Number (Optional)")
                                .font(theme.typography.subheadline)
                                .foregroundColor(colors.textSecondary)
                            
                            TextField("+1 (555) 123-4567", text: $phoneNumber)
                                .font(theme.typography.body)
                                .keyboardType(.phonePad)
                                .padding(UnifiedTheme.Spacing.md)
                                .background(colors.surface)
                                .cornerRadius(UnifiedTheme.CornerRadius.lg)
                                .disabled(selectedNominee != nil)
                        }
                        
                        VStack(alignment: .leading, spacing: UnifiedTheme.Spacing.xs) {
                            Text("Email (Optional)")
                                .font(theme.typography.subheadline)
                                .foregroundColor(colors.textSecondary)
                            
                            TextField("email@example.com", text: $email)
                                .font(theme.typography.body)
                                .keyboardType(.emailAddress)
                                .textInputAutocapitalization(.never)
                                .padding(UnifiedTheme.Spacing.md)
                                .background(colors.surface)
                                .cornerRadius(UnifiedTheme.CornerRadius.lg)
                                .disabled(selectedNominee != nil)
                        }
                        
                        if selectedVault != nil {
                            StandardCard {
                                HStack {
                                    Image(systemName: "lock.shield.fill")
                                        .foregroundColor(colors.info)
                                    Text("Vault: \(vaultName)")
                                        .font(theme.typography.caption)
                                        .foregroundColor(colors.textSecondary)
                                }
                            }
                        }
                        
                        StandardCard {
                            VStack(alignment: .leading, spacing: UnifiedTheme.Spacing.xs) {
                                HStack {
                                    Image(systemName: "info.circle.fill")
                                        .foregroundColor(colors.info)
                                    Text("Invitation Process")
                                        .font(theme.typography.caption)
                                        .foregroundColor(colors.textPrimary)
                                        .fontWeight(.semibold)
                                }
                                
                                Text("An invitation will be sent via Messages app. The nominee will receive a secure link to accept access to this vault.")
                                    .font(theme.typography.caption)
                                    .foregroundColor(colors.textSecondary)
                            }
                        }
                        
                        Button {
                            sendInvitation()
                        } label: {
                            if isLoading {
                                ProgressView()
                                    .tint(.white)
                            } else {
                                Text("Send Invitation")
                            }
                        }
                        .buttonStyle(PrimaryButtonStyle())
                        .disabled(vaultName.isEmpty || recipientName.isEmpty || isLoading)
                    }
                    .padding(UnifiedTheme.Spacing.lg)
                }
            }
            .navigationTitle("Invite Nominee")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .topBarLeading) {
                    Button("Cancel") {
                        onCancel()
                    }
                    .foregroundColor(colors.primary)
                }
            }
            .onAppear {
                loadVaults()
            }
            .alert("Error", isPresented: $showError) {
                Button("OK", role: .cancel) { }
            } message: {
                Text(errorMessage)
            }
        }
    }
    
    private func sendInvitation() {
        guard !vaultName.isEmpty, !recipientName.isEmpty else {
            errorMessage = "Please select a vault and enter recipient name"
            showError = true
            return
        }
        
        guard let vault = selectedVault else {
            errorMessage = "Please select a vault"
            showError = true
            return
        }
        
        isLoading = true
        
        Task {
            do {
                // Create nominee if not using existing one
                let inviteToken: String
                
                if let existingNominee = selectedNominee {
                    // Resending invitation to existing nominee
                    inviteToken = existingNominee.inviteToken
                    print("✅ Resending invitation to existing nominee: \(existingNominee.name)")
                } else {
                    // Create new nominee - initialize ModelContext if needed
                    var context: ModelContext
                    if let existingContext = modelContext {
                        context = existingContext
                    } else {
                        let schema = Schema([Nominee.self, Vault.self, User.self])
                        let modelConfiguration = ModelConfiguration(
                            schema: schema,
                            isStoredInMemoryOnly: false,
                            cloudKitDatabase: .automatic
                        )
                        let container = try ModelContainer(for: schema, configurations: [modelConfiguration])
                        context = container.mainContext
                        await MainActor.run {
                            self.modelContext = context
                        }
                    }
                    
                    // Get current user ID
                    let userDescriptor = FetchDescriptor<User>()
                    let users = try context.fetch(userDescriptor)
                    guard let currentUser = users.first else {
                        throw NSError(domain: "MessageExtension", code: 1, userInfo: [NSLocalizedDescriptionKey: "No user found. Please sign in to the main app first."])
                    }
                    
                    // Create nominee
                    let nominee = Nominee(
                        name: recipientName,
                        phoneNumber: phoneNumber.isEmpty ? nil : phoneNumber,
                        email: email.isEmpty ? nil : email
                    )
                    nominee.vault = vault
                    nominee.invitedByUserID = currentUser.id
                    
                    if vault.nomineeList == nil {
                        vault.nomineeList = []
                    }
                    vault.nomineeList?.append(nominee)
                    
                    context.insert(nominee)
                    try context.save()
                    
                    inviteToken = nominee.inviteToken
                    print("✅ Created nominee: \(nominee.name) with token: \(inviteToken)")
                }
                
                // Send invitation with the token
                await MainActor.run {
                    onSendInvitation(inviteToken, vaultName, recipientName)
                    isLoading = false
                }
            } catch {
                print("❌ Failed to create/send invitation: \(error.localizedDescription)")
                await MainActor.run {
                    errorMessage = "Failed to create invitation: \(error.localizedDescription)"
                    showError = true
                    isLoading = false
                }
            }
        }
    }
    
    private func loadPendingNominees(for vault: Vault) {
        Task {
            do {
                let schema = Schema([Nominee.self, Vault.self])
                let modelConfiguration = ModelConfiguration(
                    schema: schema,
                    isStoredInMemoryOnly: false,
                    cloudKitDatabase: .automatic
                )
                
                let container = try ModelContainer(for: schema, configurations: [modelConfiguration])
                let context = container.mainContext
                
                let vaultID = vault.id
                let descriptor = FetchDescriptor<Nominee>(
                    predicate: #Predicate { nominee in
                        nominee.vault?.id == vaultID && nominee.statusRaw == "pending"
                    },
                    sortBy: [SortDescriptor(\.invitedAt, order: .reverse)]
                )
                
                let nominees = try context.fetch(descriptor)
                
                await MainActor.run {
                    pendingNominees = nominees
                }
            } catch {
                print("❌ Failed to load pending nominees: \(error.localizedDescription)")
            }
        }
    }
    
    private func loadVaults() {
        Task {
            do {
                // Create ModelContainer for MessageExtension
                let schema = Schema([
                    User.self,
                    Vault.self
                ])
                
                let modelConfiguration = ModelConfiguration(
                    schema: schema,
                    isStoredInMemoryOnly: false,
                    cloudKitDatabase: .automatic
                )
                
                let container = try ModelContainer(for: schema, configurations: [modelConfiguration])
                let context = container.mainContext
                
                // Fetch vaults
                let descriptor = FetchDescriptor<Vault>(
                    sortBy: [SortDescriptor(\.createdAt, order: .reverse)]
                )
                
                let fetchedVaults = try context.fetch(descriptor)
                
                await MainActor.run {
                    vaults = fetchedVaults.filter { !$0.isSystemVault }
                    if let firstVault = vaults.first {
                        selectedVault = firstVault
                        vaultName = firstVault.name
                    }
                }
            } catch {
                print("❌ Failed to load vaults: \(error.localizedDescription)")
            }
        }
    }
}

